const path = require('path');

// Require paths relative to: server/storage/plugins/agent-skills/anc-pricing/handler.js
// Target: server/utils/AncPricingEngine.js and server/utils/AncDocumentService.js
const AncPricingEngine = require('../../../../utils/AncPricingEngine');
const AncDocumentService = require('../../../../utils/AncDocumentService');

module.exports.runtime = {
  handler: async function ({ width, height, environment, margin, address }) {
    try {
      if (!width || !height) {
        return "Error: Missing width or height parameters. Please provide dimensions in feet.";
      }

      // Convert margin to decimal if passed (e.g. 32 -> 0.32 or 0.32 -> 0.32)
      let targetMargin = 0.30;
      if (margin) {
        const m = parseFloat(margin);
        targetMargin = m > 1 ? m / 100 : m;
      }

      this.logger(`[ANC Custom Skill] Calculating: ${width}x${height} ${environment} with ${targetMargin * 100}% margin. Address: ${address || 'N/A'}`);
      this.introspect(`Calculating hardware and construction costs for a ${width}x${height} ${environment || 'indoor'} display at ${targetMargin * 100}% margin...`);

      // 1. Run Math (Ensure numbers)
      const quote = AncPricingEngine.calculate(Number(width), Number(height), environment || 'indoor', targetMargin, address);

      // 2. Generate File
      this.introspect(`Generating detailed internal audit Excel file...`);
      const filename = await AncDocumentService.generateAuditFile(quote, "agent-generated");

      // 3. Construct Download Link
      const baseUrl = process.env.BASE_URL || 'https://basheer-everythingllm.x0uyzh.easypanel.host';
      const downloadUrl = `${baseUrl}/api/system/download/${filename}`;

      // 4. Return Final Response
      // Return a professional Markdown response that the LLM is expected to use directly.
      return `### 📊 ANC Sports Official Quote Generated
**Labor Type:** Union (MANDATORY)
**Target Margin:** ${targetMargin * 100}%
**Total Project Price:** ${quote.tabs.summary.sellPrice.toLocaleString('en-US', { style: 'currency', currency: 'USD' })}

✅ **The mandatory 8-Tab Auditor Excel has been generated and is ready for download below:**

🔗 **[DOWNLOAD_OFFICIAL_AUDIT_EXCEL](${downloadUrl})**

*Note: This link is generated by the internal ANC calculation engine. Internal Filename: ${filename}*`;

    } catch (error) {
      this.logger(`ANC Skill Error: ${error.message}`);
      return `Error in calculation: ${error.message}`;
    }
  }
};
